Always explicitely use utf-8 when reading/writing files
Explicitely pass utf-8 as an encoding to fix the following errors in Windows.

UnicodeEncodeError: 'charmap' codec can't encode characters in position 106-108: character maps to <undefined>
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2514: character maps to <undefined>

It uses the locale encoding by default otherwise which is probably
not what we want when generating files, and also explodes with Unicode
on Windows.

Note: Missing encoding arguments can be detected on all platforms starting with
Python 3.10 if the PYTHONWARNDEFAULTENCODING env var is set, see
https://peps.python.org/pep-0597 for more details.